server:
  port: 8086


spring:
  application:
    name: admin-console
  security:
    user:
      name: admin
      password: password



eureka:
  client:
    healthcheck:
      enabled: true
    eureka-server-total-connections: 200
    service-url:
      defaultZone: http://eureka:password@${EUREKA_SERVICE_URL:localhost}:8761/eureka
    registry-fetch-interval-seconds: 5

  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    home-page-url-path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


